name: ci
on:
  pull_request:
    branches:
      - "**"
  push:
    branches: [main, staging, development]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - name: Install dependencies
        run: go get ./...
  analyze:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - name: Install dependencies
        run: go get ./...
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  lint:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - name: Install dependencies
        run: go get ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.53
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
          check-latest: true
      - name: Install dependencies
        run: go get ./...
      - name: Run Tests
        run: go test ./...
